repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py36-plus
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy --config-file setup.cfg
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: darglint
        name: darglint
        entry: poetry run darglint
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8 --config setup.cfg
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint --rcfile pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest -c setup.cfg
        types: [python]
        language: system
        pass_filenames: false
        always_run: true
